#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f LightSequenceFSM.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace LightSequenceFSM.sv --exe LightSequenceFSM_tb.cpp

# build C++ projects via make automatically generated by Verilator
make -j -C obj_dir/ -f VLightSequenceFSM.mk VLightSequenceFSM

# run executable simulation file
obj_dir/VLightSequenceFSM
